name: Rodar Robo Emprego Motorista

name: Rodar Robo Emprego Motorista

on:
  workflow_dispatch: # Isso aqui ativa o botão manual no painel!
  schedule:
    - cron: '0 9,15 * * *' # Mantém o seu horário automático se houver

jobs:
  executar-robo:
    runs-on: ubuntu-latest

    steps:
    - name: Baixando os arquivos do seu GitHub
      uses: actions/checkout@v4

    - name: Instalando o Python na Nuvem
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Run python main.py
        env:
          BLOG_ID: ${{ secrets.BLOG_ID }}
          BLOGGER_CLIENT_ID: ${{ secrets.BLOGGER_CLIENT_ID }}
          BLOGGER_CLIENT_SECRET: ${{ secrets.BLOGGER_CLIENT_SECRET }}
          BLOGGER_REFRESH_TOKEN: ${{ secrets.BLOGGER_REFRESH_TOKEN }}
        run: python main.py
